/* =========================================================
 * ClassPay 3.2: 商品市場・会社間取引・週次処理センター
 * ========================================================= */

function _v32Sheet_(key,name,header){
  const sheetName=SHEETS[key]||name,existing=SpreadsheetApp.getActive().getSheetByName(sheetName);
  return existing||_ensureColumns_(_ensureSheetWithHeader_(sheetName,header),header);
}
function _productSheet_(){return _v32Sheet_("PRODUCT_CATALOG","ProductCatalog",["productId","createdAt","updatedAt","shopId","shopName","name","description","price","stock","soldCount","isActive"]);}
function _productOrderSheet_(){return _v32Sheet_("PRODUCT_ORDERS","ProductOrders",["orderId","orderedAt","productId","productName","sellerShopId","sellerShopName","buyerUserId","buyerUserName","quantity","totalAmount","status","fulfilledAt","cancelledAt","note","txId"]);}
function _companyContractSheet_(){return _v32Sheet_("COMPANY_CONTRACTS","CompanyContracts",["contractId","createdAt","buyerShopId","buyerShopName","sellerShopId","sellerShopName","title","description","quotedAmount","status","respondedAt","acceptedAt","deliveredAt","paidAt","note","outTxId","inTxId"]);}
function _weeklySettlementSheet_(){return _v32Sheet_("WEEKLY_SETTLEMENTS","WeeklySettlements",["settlementId","weekKey","component","startedAt","completedAt","status","amount","detail","error"]);}

function _ensureConfigDefaultV32_(key,value){
  const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.CONFIG);
  if(!sh)return;
  const v=sh.getDataRange().getValues();
  if(v.slice(1).some(r=>String(r[0]||"").trim()===key))return;
  _setConfigValue_(key,value);
}
function setupClassPayV32(){
  _ensureColumns_(_productSheet_(),["productId","createdAt","updatedAt","shopId","shopName","name","description","price","stock","soldCount","isActive"]);
  _ensureColumns_(_productOrderSheet_(),["orderId","orderedAt","productId","productName","sellerShopId","sellerShopName","buyerUserId","buyerUserName","quantity","totalAmount","status","fulfilledAt","cancelledAt","note","txId"]);
  _ensureColumns_(_companyContractSheet_(),["contractId","createdAt","buyerShopId","buyerShopName","sellerShopId","sellerShopName","title","description","quotedAmount","status","respondedAt","acceptedAt","deliveredAt","paidAt","note","outTxId","inTxId"]);
  _ensureColumns_(_weeklySettlementSheet_(),["settlementId","weekKey","component","startedAt","completedAt","status","amount","detail","error"]);
  _ensureConfigDefaultV32_("STOCK_DAILY_LIMIT",2);
  _ensureConfigDefaultV32_("STOCK_REASON_REQUIRED","TRUE");
  _ensureConfigDefaultV32_("WEEKLY_TAX_AMOUNT",0);
  _ensureConfigDefaultV32_("WEEKLY_USER_INTEREST_RATE",5);
  _ensureConfigDefaultV32_("WEEKLY_SHOP_INTEREST_RATE",0);
  return {ok:true,version:"3.2",sheets:["ProductCatalog","ProductOrders","CompanyContracts","WeeklySettlements"]};
}

function _productDtoV32_(x){return {productId:String(x.productId||""),createdAt:String(x.createdAt||""),updatedAt:String(x.updatedAt||""),shopId:String(x.shopId||""),shopName:String(x.shopName||""),name:String(x.name||""),description:String(x.description||""),price:Number(x.price||0),stock:Number(x.stock||0),soldCount:Number(x.soldCount||0),isActive:_isTrue_(x.isActive)};}
function _productRowsV32_(){return _rowsByHeader_(_productSheet_()).map(x=>Object.assign(_productDtoV32_(x),{rowNumber:x.rowNumber}));}
function _orderDtoV32_(x){return {orderId:String(x.orderId||""),orderedAt:String(x.orderedAt||""),productId:String(x.productId||""),productName:String(x.productName||""),sellerShopId:String(x.sellerShopId||""),sellerShopName:String(x.sellerShopName||""),buyerUserId:String(x.buyerUserId||""),buyerUserName:String(x.buyerUserName||""),quantity:Number(x.quantity||0),totalAmount:Number(x.totalAmount||0),status:String(x.status||"").toUpperCase(),fulfilledAt:String(x.fulfilledAt||""),cancelledAt:String(x.cancelledAt||""),note:String(x.note||""),txId:String(x.txId||"")};}
function _orderRowsV32_(){return _rowsByHeader_(_productOrderSheet_()).map(x=>Object.assign(_orderDtoV32_(x),{rowNumber:x.rowNumber})).reverse();}

function api_publicProductsV32(){
  return _productRowsV32_().filter(x=>x.isActive&&(x.stock===-1||x.stock>0)).sort((a,b)=>a.shopName.localeCompare(b.shopName,"ja")||a.name.localeCompare(b.name,"ja"));
}
function api_companyProductsV32(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return {products:_productRowsV32_().filter(x=>x.shopId===s.shopId),orders:_orderRowsV32_().filter(x=>x.sellerShopId===s.shopId).slice(0,100)};}
function api_companySaveProductV32(payload){
  payload=payload||{};return lockRun_(()=>{const s=_companyPass_(payload.shopId,payload.companyPass),name=String(payload.name||"").trim(),description=String(payload.description||"").trim(),price=Math.floor(Number(payload.price||0)),stock=Math.floor(Number(payload.stock));if(!name||!description)throw new Error("商品・サービス名と説明を入力してください");if(!(price>0))throw new Error("価格は1 Pay以上にしてください");if(!Number.isFinite(stock)||stock<-1)throw new Error("在庫は0以上、無制限は-1にしてください");const sh=_productSheet_(),id=String(payload.productId||"").trim()||"P-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMddHHmmss")+"-"+uuid_().slice(0,4).toUpperCase(),old=_productRowsV32_().find(x=>x.productId===id);if(old&&old.shopId!==s.shopId)throw new Error("この商品は編集できません");_writeByHeader_(sh,old?old.rowNumber:0,{productid:id,createdat:old?old.createdAt:_fmtJst_(new Date()),updatedat:_fmtJst_(new Date()),shopid:s.shopId,shopname:s.shopName,name,description,price,stock,soldcount:old?old.soldCount:0,isactive:payload.isActive!==false},["productid","shopid","name","price","stock","isactive"]);return {ok:true,productId:id,message:old?"商品・サービスを更新しました":"商品・サービスを公開しました"};});
}
function api_companySetProductActiveV32(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return lockRun_(()=>{const sh=_productSheet_(),p=_productRowsV32_().find(x=>x.productId===String(payload.productId||""));if(!p||p.shopId!==s.shopId)throw new Error("商品・サービスが見つかりません");_writeByHeader_(sh,p.rowNumber,{isactive:payload.isActive===true,updatedat:_fmtJst_(new Date())},["productid","isactive"]);return {ok:true,message:payload.isActive===true?"販売を再開しました":"販売を停止しました"};});}
function api_userBuyProductV32(payload){
  payload=payload||{};return lockRun_(()=>{const u=_assertPin_(String(payload.userId||"").trim().toUpperCase(),payload.pin),id=String(payload.productId||""),qty=Math.floor(Number(payload.quantity||1)),sh=_productSheet_(),p=_productRowsV32_().find(x=>x.productId===id);if(!p||!p.isActive)throw new Error("この商品・サービスは現在購入できません");if(!(qty>0))throw new Error("数量は1以上にしてください");if(p.stock!==-1&&p.stock<qty)throw new Error("在庫が不足しています");const seller=_findShop_(p.shopId),buyer=_findUser_(u.userId),total=p.price*qty;if(!seller||!seller.active)throw new Error("販売会社が見つかりません");if(buyer.balance<total)throw new Error("残高が足りません");buyer.sh.getRange(buyer.row,buyer.cBal).setValue(buyer.balance-total);seller.sh.getRange(seller.row,seller.cBal).setValue(seller.balance+total);const txId=uuid_(),orderId="O-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMddHHmmss")+"-"+uuid_().slice(0,4).toUpperCase(),at=_fmtJst_(new Date());_appendTx_({txId,at,type:"PRODUCT_BUY",userId:buyer.userId,userName:buyer.name,shopId:seller.shopId,shopName:seller.shopName,amount:total,status:"OK",note:p.name+" × "+qty,meta:JSON.stringify({orderId,productId:id,quantity:qty})});_writeByHeader_(_productOrderSheet_(),0,{orderid:orderId,orderedat:at,productid:id,productname:p.name,sellershopid:p.shopId,sellershopname:p.shopName,buyeruserid:buyer.userId,buyerusername:buyer.name,quantity:qty,totalamount:total,status:"PAID",note:String(payload.note||""),txid:txId},["orderid","productid","sellershopid","buyeruserid","status"]);_writeByHeader_(sh,p.rowNumber,{stock:p.stock===-1?-1:p.stock-qty,soldcount:p.soldCount+qty,updatedat:at},["productid","stock","soldcount"]);return {ok:true,orderId,totalAmount:total,newBalance:buyer.balance-total,message:"購入・申込みが完了しました"};});
}
function api_userProductOrdersV32(userId,pin){const u=_assertPin_(String(userId||"").trim().toUpperCase(),pin);return _orderRowsV32_().filter(x=>x.buyerUserId===u.userId).slice(0,50);}
function api_companyCompleteOrderV32(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return lockRun_(()=>{const sh=_productOrderSheet_(),o=_orderRowsV32_().find(x=>x.orderId===String(payload.orderId||""));if(!o||o.sellerShopId!==s.shopId)throw new Error("注文が見つかりません");if(o.status!=="PAID")throw new Error("この注文は処理済みです");_writeByHeader_(sh,o.rowNumber,{status:"FULFILLED",fulfilledat:_fmtJst_(new Date()),note:String(payload.note||o.note||"")},["orderid","status"]);return {ok:true,message:"提供完了として記録しました"};});}

function _contractDtoV32_(x){return {contractId:String(x.contractId||""),createdAt:String(x.createdAt||""),buyerShopId:String(x.buyerShopId||""),buyerShopName:String(x.buyerShopName||""),sellerShopId:String(x.sellerShopId||""),sellerShopName:String(x.sellerShopName||""),title:String(x.title||""),description:String(x.description||""),quotedAmount:Number(x.quotedAmount||0),status:String(x.status||"").toUpperCase(),respondedAt:String(x.respondedAt||""),acceptedAt:String(x.acceptedAt||""),deliveredAt:String(x.deliveredAt||""),paidAt:String(x.paidAt||""),note:String(x.note||"")};}
function _contractRowsV32_(){return _rowsByHeader_(_companyContractSheet_()).map(x=>Object.assign(_contractDtoV32_(x),{rowNumber:x.rowNumber})).reverse();}
function api_companyContractsV32(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return _contractRowsV32_().filter(x=>x.buyerShopId===s.shopId||x.sellerShopId===s.shopId).slice(0,100);}
function api_companyCreateContractV32(payload){payload=payload||{};return lockRun_(()=>{const buyer=_companyPass_(payload.shopId,payload.companyPass),seller=_findShop_(String(payload.sellerShopId||"").trim().toUpperCase()),title=String(payload.title||"").trim(),description=String(payload.description||"").trim();if(!seller||!seller.active||seller.shopId===buyer.shopId)throw new Error("依頼先の会社が不正です");if(!title||!description)throw new Error("依頼名と依頼内容を入力してください");const id="C-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMddHHmmss")+"-"+uuid_().slice(0,4).toUpperCase();_writeByHeader_(_companyContractSheet_(),0,{contractid:id,createdat:_fmtJst_(new Date()),buyershopid:buyer.shopId,buyershopname:buyer.shopName,sellershopid:seller.shopId,sellershopname:seller.shopName,title,description,quotedamount:Math.max(0,Math.floor(Number(payload.requestedAmount||0))),status:"REQUESTED",note:String(payload.note||"")},["contractid","buyershopid","sellershopid","title","status"]);return {ok:true,contractId:id,message:"仕事を依頼しました"};});}
function api_companyRespondContractV32(payload){payload=payload||{};const seller=_companyPass_(payload.shopId,payload.companyPass);return lockRun_(()=>{const sh=_companyContractSheet_(),c=_contractRowsV32_().find(x=>x.contractId===String(payload.contractId||"")),decision=String(payload.decision||"").toUpperCase(),amount=Math.floor(Number(payload.quotedAmount||0));if(!c||c.sellerShopId!==seller.shopId)throw new Error("依頼が見つかりません");if(c.status!=="REQUESTED")throw new Error("この依頼は処理済みです");if(!["QUOTED","REJECTED"].includes(decision))throw new Error("見積りまたは辞退を選択してください");if(decision==="QUOTED"&&!(amount>0))throw new Error("見積額は1 Pay以上にしてください");_writeByHeader_(sh,c.rowNumber,{status:decision,quotedamount:decision==="QUOTED"?amount:0,respondedat:_fmtJst_(new Date()),note:String(payload.note||"")},["contractid","status"]);return {ok:true,status:decision,message:decision==="QUOTED"?"見積りを送りました":"依頼を辞退しました"};});}
function api_companyAcceptContractV32(payload){payload=payload||{};const buyer=_companyPass_(payload.shopId,payload.companyPass);return lockRun_(()=>{const sh=_companyContractSheet_(),c=_contractRowsV32_().find(x=>x.contractId===String(payload.contractId||""));if(!c||c.buyerShopId!==buyer.shopId)throw new Error("依頼が見つかりません");if(c.status!=="QUOTED")throw new Error("この見積りは処理できません");if(buyer.balance<c.quotedAmount)throw new Error("支払い予定額に対して会社残高が不足しています");_writeByHeader_(sh,c.rowNumber,{status:"ACCEPTED",acceptedat:_fmtJst_(new Date())},["contractid","status"]);return {ok:true,message:"見積りを承認しました。納品後に支払います"};});}
function api_companyDeliverContractV32(payload){payload=payload||{};const seller=_companyPass_(payload.shopId,payload.companyPass);return lockRun_(()=>{const sh=_companyContractSheet_(),c=_contractRowsV32_().find(x=>x.contractId===String(payload.contractId||""));if(!c||c.sellerShopId!==seller.shopId)throw new Error("契約が見つかりません");if(c.status!=="ACCEPTED")throw new Error("この契約は納品できません");_writeByHeader_(sh,c.rowNumber,{status:"DELIVERED",deliveredat:_fmtJst_(new Date()),note:String(payload.note||c.note||"")},["contractid","status"]);return {ok:true,message:"納品を報告しました"};});}
function api_companyPayContractV32(payload){payload=payload||{};const buyerAuth=_companyPass_(payload.shopId,payload.companyPass);return lockRun_(()=>{const sh=_companyContractSheet_(),c=_contractRowsV32_().find(x=>x.contractId===String(payload.contractId||""));if(!c||c.buyerShopId!==buyerAuth.shopId)throw new Error("契約が見つかりません");if(c.status!=="DELIVERED")throw new Error("納品報告後に支払えます");const buyer=_findShop_(c.buyerShopId),seller=_findShop_(c.sellerShopId);if(!buyer||!seller||!buyer.active||!seller.active)throw new Error("会社が見つからないか停止中です");if(buyer.balance<c.quotedAmount)throw new Error("会社残高が不足しています");buyer.sh.getRange(buyer.row,buyer.cBal).setValue(buyer.balance-c.quotedAmount);seller.sh.getRange(seller.row,seller.cBal).setValue(seller.balance+c.quotedAmount);const at=_fmtJst_(new Date()),outId=uuid_(),inId=uuid_();_appendTx_({txId:outId,at,type:"CONTRACT_OUT",userId:"",userName:"",shopId:buyer.shopId,shopName:buyer.shopName,amount:-c.quotedAmount,status:"OK",note:c.sellerShopName+"へ："+c.title,meta:JSON.stringify({contractId:c.contractId})});_appendTx_({txId:inId,at,type:"CONTRACT_IN",userId:"",userName:"",shopId:seller.shopId,shopName:seller.shopName,amount:c.quotedAmount,status:"OK",note:c.buyerShopName+"から："+c.title,meta:JSON.stringify({contractId:c.contractId})});_writeByHeader_(sh,c.rowNumber,{status:"PAID",paidat:at,outtxid:outId,intxid:inId},["contractid","status"]);return {ok:true,amount:c.quotedAmount,message:"納品を確認し、支払いが完了しました"};});}

function api_companyActivityDashboardV32(payload){
  payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass),since=Date.now()-7*86400000,tx=_rowsByHeader_(_getTxSheet_()).filter(x=>String(x.shopId||"").toUpperCase()===s.shopId&&_stockTime_(x.at)>=since),inTypes=["PAY","PRODUCT_BUY","STOCK_BUY","CONTRACT_IN","SHOP_DIST","INTEREST_S","WEEKLY_SUPPORT"],outTypes=["SALARY","STOCK_SELL","CONTRACT_OUT","SHOP_WD"],income=tx.reduce((n,x)=>n+(inTypes.includes(String(x.type||"").toUpperCase())?Math.abs(Number(x.amount||0)):0),0),expense=tx.reduce((n,x)=>n+(outTypes.includes(String(x.type||"").toUpperCase())?Math.abs(Number(x.amount||0)):0),0),members=_membershipHistoryRows_({shopId:s.shopId}).filter(x=>x.isActive).length,reports=_weeklyReportRows_({shopId:s.shopId}),orders=_orderRowsV32_().filter(x=>x.sellerShopId===s.shopId),contracts=_contractRowsV32_().filter(x=>x.buyerShopId===s.shopId||x.sellerShopId===s.shopId);return {version:"3.2",shop:{shopId:s.shopId,shopName:s.shopName,balance:s.balance},week:{income,expense,profit:income-expense,transactions:tx.length},members,products:_productRowsV32_().filter(x=>x.shopId===s.shopId).length,orders:{pending:orders.filter(x=>x.status==="PAID").length,total:orders.length},contracts:{actionRequired:contracts.filter(x=>(x.sellerShopId===s.shopId&&["REQUESTED","ACCEPTED"].includes(x.status))||(x.buyerShopId===s.shopId&&["QUOTED","DELIVERED"].includes(x.status))).length,total:contracts.length},weeklyReport:reports[0]||null};
}
function api_userEconomyV32(userId,pin){const u=_assertPin_(String(userId||"").trim().toUpperCase(),pin),orders=_orderRowsV32_().filter(x=>x.buyerUserId===u.userId).slice(0,20);return {products:api_publicProductsV32(),orders,notices:orders.slice(0,5).map(x=>({type:"ORDER",title:x.productName,detail:x.status==="PAID"?"会社が準備中です":x.status==="FULFILLED"?"提供完了になりました":"状態："+x.status}))};}

function _settlementRowsV32_(){return _rowsByHeader_(_weeklySettlementSheet_()).reverse();}
function api_adminWeeklyPreviewV32(adminPass){_assertAdminPassValue_(adminPass);const users=api_listUsers(),shops=api_listShops(),tax=Math.max(0,Number(getConfig_("WEEKLY_TAX_AMOUNT",0))),ur=Math.max(0,Number(getConfig_("WEEKLY_USER_INTEREST_RATE",5))),sr=Math.max(0,Number(getConfig_("WEEKLY_SHOP_INTEREST_RATE",0))),taxTotal=users.reduce((n,u)=>n+Math.min(Math.max(0,u.balance),tax),0),userInterest=users.reduce((n,u)=>n+Math.floor(Math.max(0,u.balance)*ur/100),0),shopInterest=shops.reduce((n,s)=>n+Math.floor(Math.max(0,s.balance)*sr/100),0),weekKey=_weekKey_(),done=_settlementRowsV32_().filter(x=>String(x.weekKey)===weekKey&&String(x.status)==="DONE").map(x=>String(x.component));return {version:"3.2",weekKey,settings:{taxAmount:tax,userInterestRate:ur,shopInterestRate:sr},counts:{users:users.length,shops:shops.length},estimate:{taxTotal,userInterest,shopInterest,governmentChange:taxTotal-userInterest-shopInterest},completed:done,history:_settlementRowsV32_().slice(0,20)};}
function _recordSettlementV32_(weekKey,component,status,amount,detail,error,id){const sh=_weeklySettlementSheet_(),old=id&&_rowsByHeader_(sh).find(x=>String(x.settlementId)===id),sid=id||"WS-"+weekKey.replace(/-/g,"")+"-"+component;_writeByHeader_(sh,old?old.rowNumber:0,{settlementid:sid,weekkey:weekKey,component,startedat:old?old.startedAt:_fmtJst_(new Date()),completedat:status==="DONE"?_fmtJst_(new Date()):"",status,amount:Number(amount||0),detail:String(detail||""),error:String(error||"")},["settlementid","weekkey","component","status"]);return sid;}
function _claimSettlementV32_(weekKey,component){return lockRun_(()=>{const id="WS-"+weekKey.replace(/-/g,"")+"-"+component,old=_rowsByHeader_(_weeklySettlementSheet_()).find(x=>String(x.settlementId)===id),started=old?_stockTime_(old.startedAt):0;if(old&&String(old.status)==="DONE")return {claimed:false,id,message:"実行済み"};if(old&&String(old.status)==="RUNNING"&&Date.now()-started<600000)return {claimed:false,id,message:"別の処理で実行中"};_recordSettlementV32_(weekKey,component,"RUNNING",0,"","",id);return {claimed:true,id};});}
function api_adminRunWeeklyV32(adminPass,components){_assertAdminPassValue_(adminPass);components=(components||[]).map(x=>String(x).toUpperCase()).filter(x=>["TAX","USER_INTEREST","SHOP_INTEREST","SNAPSHOT"].includes(x));if(!components.length)throw new Error("実行する処理を選択してください");const preview=api_adminWeeklyPreviewV32(adminPass),weekKey=preview.weekKey,results=[];components.forEach(component=>{if((component==="TAX"&&preview.settings.taxAmount<=0)||(component==="USER_INTEREST"&&preview.settings.userInterestRate<=0)||(component==="SHOP_INTEREST"&&preview.settings.shopInterestRate<=0)){results.push({component,skipped:true,message:"設定値が0のため実行なし"});return;}const claim=_claimSettlementV32_(weekKey,component);if(!claim.claimed){results.push({component,skipped:true,message:claim.message});return;}const id=claim.id;try{let r,amount=0;if(component==="TAX"){r=api_phase2CollectTax(adminPass,preview.settings.taxAmount,"週次税金 "+weekKey,"CAP");amount=Number(r.totalCollected||0);}else if(component==="USER_INTEREST"){r=api_phase2UserInterest(adminPass,preview.settings.userInterestRate,"週次児童利息 "+weekKey);amount=Number(r.totalInterest||0);}else if(component==="SHOP_INTEREST"){r=api_phase2ShopInterest(adminPass,preview.settings.shopInterestRate,"週次会社利息 "+weekKey);amount=Number(r.totalInterest||0);}else{r=api_adminSaveCompanySnapshot(adminPass);amount=Number(r.count||0);}_recordSettlementV32_(weekKey,component,"DONE",amount,JSON.stringify(r),"",id);results.push({component,ok:true,amount});}catch(e){_recordSettlementV32_(weekKey,component,"FAILED",0,"",e.message,id);results.push({component,ok:false,error:e.message});}});return {ok:results.every(x=>x.ok||x.skipped),weekKey,results,preview:api_adminWeeklyPreviewV32(adminPass)};}
