/* ClassPay Phase 3: 週報・自治・公開会計・通知 */
function _phase3Sheet_(key,name,header){
  return _ensureColumns_(_ensureSheetWithHeader_(SHEETS[key]||name,header),header);
}
function _weeklyReportsSheet_(){return _phase3Sheet_("WEEKLY_REPORTS","WeeklyReports",["reportId","submittedAt","weekKey","shopId","shopName","goal","activities","contribution","teamwork","innovation","reflection","nextGoal","memberContributions","status","reviewedAt","scores","totalScore","supportAmount","reviewNote","paidTxId"]);}
function _ruleProposalsSheet_(){return _phase3Sheet_("RULE_PROPOSALS","RuleProposals",["proposalId","submittedAt","userId","userName","title","reason","benefit","concern","status","discussionNote","voteStartAt","voteEndAt","effectiveAt","closedAt"]);}
function _ruleVotesSheet_(){return _phase3Sheet_("RULE_VOTES","RuleVotes",["proposalId","userId","vote","votedAt"]);}
function _weekKey_(d){d=d||new Date();const x=new Date(d.getFullYear(),d.getMonth(),d.getDate()),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return Utilities.formatDate(x,"Asia/Tokyo","yyyy-MM-dd");}
function _rowsByHeader_(sh){const v=typeof _cpSheetValues_==="function"?_cpSheetValues_(sh):sh.getDataRange().getValues();if(v.length<2)return [];const m=_headerMap_(v[0]),headers=v[0];return v.slice(1).map((r,i)=>{const o={rowNumber:i+2};headers.forEach((h,j)=>o[String(h||"").trim()]=r[j]);return o;});}
function _companyPass_(shopId,pass){shopId=String(shopId||"").trim().toUpperCase();const s=_findShop_(shopId);if(!s||!s.active)throw new Error("会社が見つからないか停止中です");if(String(pass||"").trim()!==s.companyPass)throw new Error("会社PASSが違います");return s;}
function _weeklyReportDto_(x){let scores={};try{scores=JSON.parse(String(x.scores||"{}"));}catch(e){}return {reportId:String(x.reportId||""),submittedAt:String(x.submittedAt||""),weekKey:String(x.weekKey||""),shopId:String(x.shopId||""),shopName:String(x.shopName||""),goal:String(x.goal||""),activities:String(x.activities||""),contribution:String(x.contribution||""),teamwork:String(x.teamwork||""),innovation:String(x.innovation||""),reflection:String(x.reflection||""),nextGoal:String(x.nextGoal||""),memberContributions:String(x.memberContributions||""),status:String(x.status||"").toUpperCase(),reviewedAt:String(x.reviewedAt||""),scores,totalScore:Number(x.totalScore||0),supportAmount:Number(x.supportAmount||0),reviewNote:String(x.reviewNote||""),paidTxId:String(x.paidTxId||"")};}
function _weeklyReportRows_(filter){filter=filter||{};const rows=_rowsByHeader_(_weeklyReportsSheet_()).map(_weeklyReportDto_);return rows.filter(x=>(!filter.shopId||x.shopId===filter.shopId)&&(!filter.status||x.status===filter.status)&&(!filter.weekKey||x.weekKey===filter.weekKey)).reverse();}
function api_companySubmitWeeklyReport(payload){return lockRun_(()=>{payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass),weekKey=String(payload.weekKey||_weekKey_()).trim();for(const k of ["goal","activities","contribution","reflection","nextGoal"])if(!String(payload[k]||"").trim())throw new Error("週報の必須項目を入力してください");if(_weeklyReportRows_({shopId:s.shopId,weekKey}).some(x=>x.status!=="REJECTED"))throw new Error("この週の週報は提出済みです");const id="WR-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMdd-HHmmss")+"-"+uuid_().slice(0,5).toUpperCase();_writeByHeader_(_weeklyReportsSheet_(),0,{reportid:id,submittedat:_fmtJst_(new Date()),weekkey:weekKey,shopid:s.shopId,shopname:s.shopName,goal:String(payload.goal).trim(),activities:String(payload.activities).trim(),contribution:String(payload.contribution).trim(),teamwork:String(payload.teamwork||"").trim(),innovation:String(payload.innovation||"").trim(),reflection:String(payload.reflection).trim(),nextgoal:String(payload.nextGoal).trim(),membercontributions:String(payload.memberContributions||"").trim(),status:"PENDING"},["reportid","weekkey","shopid","status"]);return {ok:true,reportId:id,status:"PENDING",message:"週報を政府へ提出しました"};});}
function api_companyWeeklyReports(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return _weeklyReportRows_({shopId:s.shopId});}
function api_adminWeeklyReports(adminPass,status){_assertAdminPassValue_(adminPass);return _weeklyReportRows_({status:String(status||"").toUpperCase()});}
function api_adminReviewWeeklyReport(adminPass,payload){_assertAdminPassValue_(adminPass);return lockRun_(()=>{payload=payload||{};const id=String(payload.reportId||""),decision=String(payload.decision||"").toUpperCase(),sh=_weeklyReportsSheet_(),raw=_rowsByHeader_(sh).find(x=>String(x.reportId)===id);if(!raw)throw new Error("週報が見つかりません");if(String(raw.status).toUpperCase()!=="PENDING")throw new Error("この週報は処理済みです");if(!["APPROVED","REJECTED"].includes(decision))throw new Error("承認または却下を選択してください");const m=_headerMap_(sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0]),set=(n,v)=>sh.getRange(raw.rowNumber,m.idx(n)+1).setValue(v),keys=["continuity","contribution","collaboration","innovation","reflection"],scores={};let total=0;keys.forEach(k=>{const n=Math.max(0,Math.min(2,Number((payload.scores||{})[k]||0)));scores[k]=n;total+=n;});let support=0,txId="";if(decision==="APPROVED"){support=payload.supportAmount===""||payload.supportAmount===undefined?total*Number(getConfig_("SUPPORT_PER_POINT",10)):Number(payload.supportAmount);if(!Number.isFinite(support)||support<0)throw new Error("支援金が不正です");const gov=_getGovernmentAccount_(),shop=_findShop_(String(raw.shopId));if(!shop||!shop.active)throw new Error("会社が見つかりません");if(gov.balance<support)throw new Error("政府残高が不足しています");if(support>0){shop.sh.getRange(shop.row,shop.cBal).setValue(shop.balance+support);txId=uuid_();_phase2GovernmentMove_(-support,"WEEKLY_SUPPORT_OUT",String(raw.shopName)+" 週報支援金",id);_appendTx_({txId,at:_fmtJst_(new Date()),type:"WEEKLY_SUPPORT",userId:"",userName:"",shopId:shop.shopId,shopName:shop.shopName,amount:support,status:"OK",note:"週報評価 "+total+"点"});}}set("status",decision);set("reviewedat",_fmtJst_(new Date()));set("scores",JSON.stringify(scores));set("totalscore",total);set("supportamount",support);set("reviewnote",String(payload.reviewNote||""));set("paidtxid",txId);return {ok:true,status:decision,totalScore:total,supportAmount:support};});}
function api_publicCompanyActivities(limit){limit=Math.min(Math.max(Number(limit||20),1),100);return _weeklyReportRows_({status:"APPROVED"}).slice(0,limit).map(x=>({reportId:x.reportId,weekKey:x.weekKey,shopId:x.shopId,shopName:x.shopName,goal:x.goal,activities:x.activities,contribution:x.contribution,reflection:x.reflection,nextGoal:x.nextGoal,totalScore:x.totalScore,supportAmount:x.supportAmount}));}
function _ruleDto_(x,voteMap){const id=String(x.proposalId||""),c=voteMap[id]||{YES:0,NO:0,ABSTAIN:0};return {proposalId:id,submittedAt:String(x.submittedAt||""),userId:String(x.userId||""),userName:String(x.userName||""),title:String(x.title||""),reason:String(x.reason||""),benefit:String(x.benefit||""),concern:String(x.concern||""),status:String(x.status||"").toUpperCase(),discussionNote:String(x.discussionNote||""),voteStartAt:String(x.voteStartAt||""),voteEndAt:String(x.voteEndAt||""),effectiveAt:String(x.effectiveAt||""),closedAt:String(x.closedAt||""),votes:{yes:c.YES||0,no:c.NO||0,abstain:c.ABSTAIN||0}};}
function _ruleRows_(){const votes={};_rowsByHeader_(_ruleVotesSheet_()).forEach(x=>{const id=String(x.proposalId||""),v=String(x.vote||"").toUpperCase();if(!votes[id])votes[id]={YES:0,NO:0,ABSTAIN:0};if(votes[id][v]!==undefined)votes[id][v]++;});return _rowsByHeader_(_ruleProposalsSheet_()).map(x=>_ruleDto_(x,votes)).reverse();}
function api_submitRuleProposal(payload){return lockRun_(()=>{payload=payload||{};const u=_assertPin_(String(payload.userId||"").trim().toUpperCase(),payload.pin),title=String(payload.title||"").trim(),reason=String(payload.reason||"").trim(),benefit=String(payload.benefit||"").trim();if(!title||!reason||!benefit)throw new Error("提案名・提案理由・よくなることを入力してください");const id="RULE-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMdd-HHmmss")+"-"+uuid_().slice(0,5).toUpperCase();_writeByHeader_(_ruleProposalsSheet_(),0,{proposalid:id,submittedat:_fmtJst_(new Date()),userid:u.userId,username:u.name,title,reason,benefit,concern:String(payload.concern||""),status:"PROPOSED"},["proposalid","userid","title","status"]);return {ok:true,proposalId:id,message:"ルール案を先生へ提出しました"};});}
function api_publicRules(){return _ruleRows_().filter(x=>["PROPOSED","VOTING","ADOPTED"].includes(x.status));}
function api_adminRuleProposals(adminPass){_assertAdminPassValue_(adminPass);return _ruleRows_();}
function _updateRule_(id,values){const sh=_ruleProposalsSheet_(),rows=_rowsByHeader_(sh),x=rows.find(r=>String(r.proposalId)===id);if(!x)throw new Error("提案が見つかりません");_writeByHeader_(sh,x.rowNumber,values,["proposalid","status"]);return x;}
function api_adminOpenRuleVote(adminPass,payload,discussionNote,voteEndAt){_assertAdminPassValue_(adminPass);if(payload&&typeof payload==="object"){discussionNote=payload.discussionNote;voteEndAt=payload.voteEndAt;payload=payload.proposalId}const proposalId=String(payload||"");return lockRun_(()=>{const current=_ruleRows_().find(x=>x.proposalId===proposalId);if(!current||!["PROPOSED","VOTING"].includes(current.status))throw new Error("この提案は投票開始できません");_updateRule_(proposalId,{status:"VOTING",discussionnote:String(discussionNote||""),votestartat:_fmtJst_(new Date()),voteendat:String(voteEndAt||"")});return {ok:true,status:"VOTING"};});}
function api_voteRule(userId,pin,proposalId,vote){return lockRun_(()=>{const u=_assertPin_(String(userId||"").trim().toUpperCase(),pin);proposalId=String(proposalId||"");vote=String(vote||"").toUpperCase();if(!["YES","NO","ABSTAIN"].includes(vote))throw new Error("投票内容が不正です");const rule=_ruleRows_().find(x=>x.proposalId===proposalId);if(!rule||rule.status!=="VOTING")throw new Error("現在投票できない提案です");if(rule.voteEndAt){const end=new Date(String(rule.voteEndAt).replace(" ","T"));if(!isNaN(end.getTime())&&Date.now()>end.getTime())throw new Error("投票期間は終了しています")}const sh=_ruleVotesSheet_(),rows=_rowsByHeader_(sh),old=rows.find(x=>String(x.proposalId)===proposalId&&String(x.userId).toUpperCase()===u.userId);_writeByHeader_(sh,old?old.rowNumber:0,{proposalid:proposalId,userid:u.userId,vote,votedat:_fmtJst_(new Date())},["proposalid","userid","vote"]);return {ok:true,vote};});}
function api_adminCloseRuleVote(adminPass,payload,decision,effectiveAt){_assertAdminPassValue_(adminPass);let discussionNote="";if(payload&&typeof payload==="object"){decision=payload.decision;effectiveAt=payload.effectiveAt;discussionNote=payload.discussionNote;payload=payload.proposalId}const proposalId=String(payload||"");decision=String(decision||"").toUpperCase();if(!["ADOPTED","REJECTED"].includes(decision))throw new Error("採択または否決を選択してください");const current=_ruleRows_().find(x=>x.proposalId===proposalId);if(!current||!["PROPOSED","VOTING"].includes(current.status))throw new Error("処理できない提案です");_updateRule_(proposalId,{status:decision,effectiveat:String(effectiveAt||""),discussionnote:String(discussionNote||current.discussionNote||""),closedat:_fmtJst_(new Date())});return {ok:true,status:decision};}
function api_publicGovernmentDashboard(){const g=_getGovernmentAccount_(),ledger=api_phase2GovernmentLedger(getConfig_("ADMIN_PASS",""),30),totals={tax:0,rights:0,interest:0,support:0,distribution:0};ledger.forEach(x=>{const t=String(x.type);if(t.includes("TAX"))totals.tax+=x.amount;if(t.includes("RIGHTS"))totals.rights+=x.amount;if(t.includes("INTEREST"))totals.interest+=Math.abs(x.amount);if(t.includes("SUPPORT"))totals.support+=Math.abs(x.amount);if(t.includes("DISTRIBUTION"))totals.distribution+=Math.abs(x.amount);});return {balance:g.balance,totals,activities:api_publicCompanyActivities(8)};}
function api_userCivicDashboard(userId,pin,economy){
  const u=_assertPin_(String(userId||"").trim().toUpperCase(),pin),tasks=[],notices=[],companies=_getCompaniesByUserId_(u.userId);
  const retire=_retirementApplicationRows_({userId:u.userId});
  retire.slice(0,5).forEach(x=>notices.push({type:"RETIREMENT",title:x.shopName+"の退職届",detail:x.status==="PENDING"?"社長の確認待ち":x.status==="APPROVED"?"承認されました":"却下されました"}));
  companies.filter(x=>x.role==="PRESIDENT").forEach(c=>{
    const n=_retirementApplicationRows_({shopId:c.shopId,status:"PENDING"}).length;
    if(n)tasks.push({type:"RETIREMENT_REVIEW",title:c.shopName+"の退職届",detail:n+"件の確認が必要です"});
    if(!_weeklyReportRows_({shopId:c.shopId,weekKey:_weekKey_()}).length)tasks.push({type:"WEEKLY_REPORT",title:c.shopName+"の週報",detail:"今週分が未提出です"});
    if(typeof _orderRowsV32_==="function"){
      const orders=_orderRowsV32_().filter(x=>x.sellerShopId===c.shopId&&x.status==="PAID").length;
      if(orders)tasks.push({type:"PRODUCT_ORDER",title:c.shopName+"の商品・サービス",detail:orders+"件の提供待ちがあります"});
      const contracts=_contractRowsV32_().filter(x=>(x.sellerShopId===c.shopId&&["REQUESTED","ACCEPTED"].includes(x.status))||(x.buyerShopId===c.shopId&&["QUOTED","DELIVERED"].includes(x.status))).length;
      if(contracts)tasks.push({type:"COMPANY_CONTRACT",title:c.shopName+"の会社間取引",detail:contracts+"件の確認が必要です"});
    }
  });
  const marketplace=typeof _marketplaceCivic_==="function"?_marketplaceCivic_(u):null;
  if(marketplace){if(marketplace.pendingReviewCount)tasks.push({type:"EMPLOYMENT_REVIEW",title:"エントリーシートの確認",detail:marketplace.pendingReviewCount+"件の採用審査が必要です"});marketplace.applications.slice(0,5).forEach(x=>notices.push({type:"EMPLOYMENT",title:x.shopName+"へのエントリー",detail:x.status==="PENDING"?"社長の確認待ち":x.status==="APPROVED"?"採用されました":"今回は不採用でした"}));}
  economy=economy||(typeof api_userEconomyV32==="function"?api_userEconomyV32(u.userId,pin):null);
  if(economy)(economy.notices||[]).forEach(x=>notices.push(x));
  return {tasks,notices,government:api_publicGovernmentDashboard(),marketplace};
}
function _latestCompanyActivityScore_(shopId){const r=_weeklyReportRows_({shopId:String(shopId).toUpperCase(),status:"APPROVED"})[0];return r?Number(r.totalScore):null;}
