/* ClassPay Phase 3.1: 雇用市場・募集入札・会社広告 */
function _recruitmentSheet_(){return _phase3Sheet_("RECRUITMENT_POSTINGS","RecruitmentPostings",["postingId","submittedAt","shopId","shopName","title","description","positions","bidAmount","status","reviewedAt","reviewNote","publishedAt","expiresAt","paidTxId"]);}
function _employmentSheet_(){return _phase3Sheet_("EMPLOYMENT_APPLICATIONS","EmploymentApplications",["applicationId","submittedAt","postingId","shopId","shopName","userId","userName","motivation","strengths","ideas","status","reviewedAt","reviewNote","reviewedBy"]);}
function _announcementsSheet_(){return _phase3Sheet_("COMPANY_ANNOUNCEMENTS","CompanyAnnouncements",["announcementId","submittedAt","shopId","shopName","kind","title","body","eventAt","feeAmount","status","reviewedAt","reviewNote","publishedAt","expiresAt","paidTxId"]);}
function _marketplaceSetupSheets_(){_recruitmentSheet_();_employmentSheet_();_announcementsSheet_();}
function _publicitySettings_(){return {mode:String(getConfig_("PUBLICITY_MODE","GOVERNMENT")).toUpperCase(),providerName:String(getConfig_("PRIVATE_PROVIDER_NAME","")),recruitMinBid:Math.max(0,Number(getConfig_("RECRUIT_MIN_BID",10))),recruitSlots:Math.max(1,Number(getConfig_("RECRUIT_SLOTS",3))),recruitDays:Math.max(1,Number(getConfig_("RECRUIT_DAYS",7))),announcementFee:Math.max(0,Number(getConfig_("ANNOUNCEMENT_FEE",5))),announcementDays:Math.max(1,Number(getConfig_("ANNOUNCEMENT_DAYS",7)))};}
function _assertGovernmentPublicity_(){const s=_publicitySettings_();if(s.mode==="DISABLED")throw new Error("政府による募集・告知の受付は停止中です");if(s.mode==="PRIVATE")throw new Error((s.providerName||"民間事業者")+"が募集・告知を運営しています");return s;}
function _marketTime_(v){const s=String(v||"").trim();if(!s)return 0;const d=new Date(s.replace(" ","T"));return isNaN(d.getTime())?0:d.getTime();}
function _marketExpiry_(days){const d=new Date();d.setDate(d.getDate()+Number(days||7));return _fmtJst_(d);}
function _recruitDto_(x){return {postingId:String(x.postingId||""),submittedAt:String(x.submittedAt||""),shopId:String(x.shopId||""),shopName:String(x.shopName||""),title:String(x.title||""),description:String(x.description||""),positions:Number(x.positions||1),bidAmount:Number(x.bidAmount||0),status:String(x.status||"").toUpperCase(),reviewedAt:String(x.reviewedAt||""),reviewNote:String(x.reviewNote||""),publishedAt:String(x.publishedAt||""),expiresAt:String(x.expiresAt||""),paidTxId:String(x.paidTxId||"")};}
function _employmentDto_(x){return {applicationId:String(x.applicationId||""),submittedAt:String(x.submittedAt||""),postingId:String(x.postingId||""),shopId:String(x.shopId||""),shopName:String(x.shopName||""),userId:String(x.userId||""),userName:String(x.userName||""),motivation:String(x.motivation||""),strengths:String(x.strengths||""),ideas:String(x.ideas||""),status:String(x.status||"").toUpperCase(),reviewedAt:String(x.reviewedAt||""),reviewNote:String(x.reviewNote||""),reviewedBy:String(x.reviewedBy||"")};}
function _announcementDto_(x){return {announcementId:String(x.announcementId||""),submittedAt:String(x.submittedAt||""),shopId:String(x.shopId||""),shopName:String(x.shopName||""),kind:String(x.kind||"NEWS").toUpperCase(),title:String(x.title||""),body:String(x.body||""),eventAt:String(x.eventAt||""),feeAmount:Number(x.feeAmount||0),status:String(x.status||"").toUpperCase(),reviewedAt:String(x.reviewedAt||""),reviewNote:String(x.reviewNote||""),publishedAt:String(x.publishedAt||""),expiresAt:String(x.expiresAt||""),paidTxId:String(x.paidTxId||"")};}
function _marketRows_(sheet,mapper){return _rowsByHeader_(sheet).map(mapper).reverse();}
function _chargeCompanyPublicity_(shopId,amount,type,note,referenceId){amount=Number(amount||0);const s=_findShop_(String(shopId||"").toUpperCase());if(!s||!s.active)throw new Error("会社が見つからないか停止中です");if(s.balance<amount)throw new Error(s.shopName+"の残高が不足しています");const txId=uuid_();if(amount>0){s.sh.getRange(s.row,s.cBal).setValue(s.balance-amount);_phase2GovernmentMove_(amount,type,note,referenceId);_appendTx_({txId,at:_fmtJst_(new Date()),type:"PUBLICITY_FEE",userId:"",userName:"",shopId:s.shopId,shopName:s.shopName,amount:-amount,status:"OK",note,meta:JSON.stringify({referenceId})});}return txId;}

function api_companySubmitRecruitment(payload){return lockRun_(()=>{payload=payload||{};const set=_assertGovernmentPublicity_(),s=_companyPass_(payload.shopId,payload.companyPass),title=String(payload.title||"").trim(),description=String(payload.description||"").trim(),positions=Math.max(1,Math.floor(Number(payload.positions||1))),bid=Math.floor(Number(payload.bidAmount||0));if(!title||!description)throw new Error("募集名と仕事内容を入力してください");if(!Number.isFinite(bid)||bid<set.recruitMinBid)throw new Error("入札額は最低 "+set.recruitMinBid+" Payです");const existing=_marketRows_(_recruitmentSheet_(),_recruitDto_).some(x=>x.shopId===s.shopId&&["PENDING_AUCTION","PUBLISHED"].includes(x.status)&&(!x.expiresAt||_marketTime_(x.expiresAt)>Date.now()));if(existing)throw new Error("この会社には審査中または掲載中の社員募集があります");const id="JOB-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMdd-HHmmss")+"-"+uuid_().slice(0,5).toUpperCase();_writeByHeader_(_recruitmentSheet_(),0,{postingid:id,submittedat:_fmtJst_(new Date()),shopid:s.shopId,shopname:s.shopName,title,description,positions,bidamount:bid,status:"PENDING_AUCTION"},["postingid","shopid","status"]);return {ok:true,postingId:id,message:"社員募集の入札へ参加しました。落札時に "+bid+" Payが引かれます"};});}
function api_companyRecruitments(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return _marketRows_(_recruitmentSheet_(),_recruitDto_).filter(x=>x.shopId===s.shopId);}
function api_adminRecruitments(adminPass){_assertAdminPassValue_(adminPass);return {settings:_publicitySettings_(),rows:_marketRows_(_recruitmentSheet_(),_recruitDto_).sort((a,b)=>{if(a.status==="PENDING_AUCTION"&&b.status!=="PENDING_AUCTION")return -1;if(b.status==="PENDING_AUCTION"&&a.status!=="PENDING_AUCTION")return 1;return b.bidAmount-a.bidAmount||a.submittedAt.localeCompare(b.submittedAt);})};}
function api_adminSettleRecruitmentAuction(adminPass){_assertAdminPassValue_(adminPass);return lockRun_(()=>{const set=_assertGovernmentPublicity_(),sh=_recruitmentSheet_(),rows=_rowsByHeader_(sh),pending=rows.map(_recruitDto_).filter(x=>x.status==="PENDING_AUCTION").sort((a,b)=>b.bidAmount-a.bidAmount||a.submittedAt.localeCompare(b.submittedAt)),active=rows.map(_recruitDto_).filter(x=>x.status==="PUBLISHED"&&_marketTime_(x.expiresAt)>Date.now()).length,slots=Math.max(0,set.recruitSlots-active),winners=[],losers=[];pending.forEach((x,i)=>{const raw=rows.find(r=>String(r.postingId)===x.postingId);if(i<slots){try{const txId=_chargeCompanyPublicity_(x.shopId,x.bidAmount,"RIGHTS_RECRUIT_AD_IN",x.shopName+" 社員募集掲載料",x.postingId);_writeByHeader_(sh,raw.rowNumber,{status:"PUBLISHED",reviewedat:_fmtJst_(new Date()),reviewnote:"入札落札",publishedat:_fmtJst_(new Date()),expiresat:_marketExpiry_(set.recruitDays),paidtxid:txId},["postingid","status"]);winners.push(x);}catch(e){_writeByHeader_(sh,raw.rowNumber,{status:"REJECTED",reviewedat:_fmtJst_(new Date()),reviewnote:e.message},["postingid","status"]);losers.push(x);}}else{_writeByHeader_(sh,raw.rowNumber,{status:"REJECTED",reviewedat:_fmtJst_(new Date()),reviewnote:"今回は落札できませんでした"},["postingid","status"]);losers.push(x);}});return {ok:true,winners:winners.length,losers:losers.length,message:winners.length+"社の募集を掲載しました"};});}
function api_publicRecruitments(){return _marketRows_(_recruitmentSheet_(),_recruitDto_).filter(x=>x.status==="PUBLISHED"&&_marketTime_(x.expiresAt)>Date.now()).sort((a,b)=>b.bidAmount-a.bidAmount);}

function api_submitEmploymentApplication(payload){return lockRun_(()=>{payload=payload||{};const u=_assertPin_(String(payload.userId||"").trim().toUpperCase(),payload.pin),postingId=String(payload.postingId||""),job=api_publicRecruitments().find(x=>x.postingId===postingId),motivation=String(payload.motivation||"").trim(),strengths=String(payload.strengths||"").trim();if(!job)throw new Error("この社員募集は終了しています");if(!motivation||!strengths)throw new Error("志望理由と自分のよさを入力してください");if(_activeCompanyMembership_(job.shopId,u.userId))throw new Error("すでにこの会社へ所属しています");if(_marketRows_(_employmentSheet_(),_employmentDto_).some(x=>x.postingId===postingId&&x.userId===u.userId&&x.status==="PENDING"))throw new Error("この募集へは申請済みです");const id="ENTRY-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMdd-HHmmss")+"-"+uuid_().slice(0,5).toUpperCase();_writeByHeader_(_employmentSheet_(),0,{applicationid:id,submittedat:_fmtJst_(new Date()),postingid:job.postingId,shopid:job.shopId,shopname:job.shopName,userid:u.userId,username:u.name,motivation,strengths,ideas:String(payload.ideas||"").trim(),status:"PENDING"},["applicationid","postingid","userid","status"]);return {ok:true,applicationId:id,message:job.shopName+"へエントリーシートを提出しました"};});}
function api_companyEmploymentApplications(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return _marketRows_(_employmentSheet_(),_employmentDto_).filter(x=>x.shopId===s.shopId);}
function api_companyReviewEmployment(payload){return lockRun_(()=>{payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass),id=String(payload.applicationId||""),decision=String(payload.decision||"").toUpperCase(),sh=_employmentSheet_(),rows=_rowsByHeader_(sh),raw=rows.find(x=>String(x.applicationId)===id);if(!raw||String(raw.shopId)!==s.shopId)throw new Error("エントリーシートが見つかりません");if(String(raw.status).toUpperCase()!=="PENDING")throw new Error("この申請は処理済みです");if(!["APPROVED","REJECTED"].includes(decision))throw new Error("承認または却下を選んでください");if(decision==="APPROVED"){const job=_marketRows_(_recruitmentSheet_(),_recruitDto_).find(x=>x.postingId===String(raw.postingId)),approved=rows.filter(x=>String(x.postingId)===String(raw.postingId)&&String(x.status).toUpperCase()==="APPROVED").length;if(job&&approved>=job.positions)throw new Error("この募集は採用予定人数に達しています");if(!_activeCompanyMembership_(s.shopId,String(raw.userId).toUpperCase()))_appendCompanyMember_(s.shopId,String(raw.userId).toUpperCase(),"MEMBER",_fmtJst_(new Date()));}_writeByHeader_(sh,raw.rowNumber,{status:decision,reviewedat:_fmtJst_(new Date()),reviewnote:String(payload.reviewNote||""),reviewedby:"PRESIDENT"},["applicationid","status"]);return {ok:true,status:decision,message:decision==="APPROVED"?"採用を承認し、社員として登録しました":"今回は不採用としました"};});}

function api_companySubmitAnnouncement(payload){return lockRun_(()=>{payload=payload||{};const set=_assertGovernmentPublicity_(),s=_companyPass_(payload.shopId,payload.companyPass),kind=String(payload.kind||"NEWS").toUpperCase(),title=String(payload.title||"").trim(),body=String(payload.body||"").trim();if(!["NEWS","EVENT"].includes(kind))throw new Error("告知の種類が不正です");if(!title||!body)throw new Error("見出しと内容を入力してください");const id="INFO-"+Utilities.formatDate(new Date(),"Asia/Tokyo","yyyyMMdd-HHmmss")+"-"+uuid_().slice(0,5).toUpperCase();_writeByHeader_(_announcementsSheet_(),0,{announcementid:id,submittedat:_fmtJst_(new Date()),shopid:s.shopId,shopname:s.shopName,kind,title,body,eventat:String(payload.eventAt||""),feeamount:set.announcementFee,status:"PENDING"},["announcementid","shopid","status"]);return {ok:true,announcementId:id,message:"政府へ掲載申請しました。承認時に "+set.announcementFee+" Payが引かれます"};});}
function api_companyAnnouncements(payload){payload=payload||{};const s=_companyPass_(payload.shopId,payload.companyPass);return _marketRows_(_announcementsSheet_(),_announcementDto_).filter(x=>x.shopId===s.shopId);}
function api_adminAnnouncements(adminPass){_assertAdminPassValue_(adminPass);return _marketRows_(_announcementsSheet_(),_announcementDto_);}
function api_adminReviewAnnouncement(adminPass,payload){_assertAdminPassValue_(adminPass);return lockRun_(()=>{payload=payload||{};const id=String(payload.announcementId||""),decision=String(payload.decision||"").toUpperCase(),sh=_announcementsSheet_(),rows=_rowsByHeader_(sh),raw=rows.find(x=>String(x.announcementId)===id);if(!raw)throw new Error("掲載申請が見つかりません");if(String(raw.status).toUpperCase()!=="PENDING")throw new Error("この申請は処理済みです");if(!["APPROVED","REJECTED"].includes(decision))throw new Error("承認または却下を選んでください");let txId="";if(decision==="APPROVED"){_assertGovernmentPublicity_();txId=_chargeCompanyPublicity_(raw.shopId,Number(raw.feeAmount||0),"RIGHTS_ANNOUNCEMENT_IN",String(raw.shopName)+" 告知掲載料",id);}_writeByHeader_(sh,raw.rowNumber,{status:decision,reviewedat:_fmtJst_(new Date()),reviewnote:String(payload.reviewNote||""),publishedat:decision==="APPROVED"?_fmtJst_(new Date()):"",expiresat:decision==="APPROVED"?_marketExpiry_(_publicitySettings_().announcementDays):"",paidtxid:txId},["announcementid","status"]);return {ok:true,status:decision,message:decision==="APPROVED"?"権利料を受領し、告知を掲載しました":"掲載申請を却下しました"};});}
function api_publicCompanyAnnouncements(){return _marketRows_(_announcementsSheet_(),_announcementDto_).filter(x=>x.status==="APPROVED"&&_marketTime_(x.expiresAt)>Date.now());}

function _marketplaceCivic_(u){const applications=_marketRows_(_employmentSheet_(),_employmentDto_).filter(x=>x.userId===u.userId),presidentShopIds=_getCompaniesByUserId_(u.userId).filter(x=>x.role==="PRESIDENT").map(x=>x.shopId),pendingReviews=_marketRows_(_employmentSheet_(),_employmentDto_).filter(x=>presidentShopIds.includes(x.shopId)&&x.status==="PENDING");return {settings:_publicitySettings_(),jobs:api_publicRecruitments(),announcements:api_publicCompanyAnnouncements(),applications,pendingReviewCount:pendingReviews.length};}
function api_publicPublicitySettings(){return _publicitySettings_();}
